<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-10-08T15:13:37 IST" name="Default suite" finished-at="2020-10-08T15:15:35 IST" duration-ms="117237">
    <groups>
    </groups>
    <test started-at="2020-10-08T15:13:37 IST" name="Default test" finished-at="2020-10-08T15:15:35 IST" duration-ms="117237">
      <class name="wave.test.cases.TestSuite">
        <test-method is-config="true" signature="setUp()[pri:0, instance:wave.test.cases.TestSuite@69504ae9]" started-at="2020-10-08T15:13:37 IST" name="setUp" finished-at="2020-10-08T15:14:34 IST" duration-ms="56408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="WAVE_TC_02()[pri:2, instance:wave.test.cases.TestSuite@69504ae9]" started-at="2020-10-08T15:14:34 IST" name="WAVE_TC_02" description="Creating An App" finished-at="2020-10-08T15:15:30 IST" duration-ms="55873" status="FAIL">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Bad pathname]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Bad pathname
at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:415)
at java.base/java.io.File.getCanonicalPath(File.java:621)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:785)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:747)
at Generic.pack.GenericType.captureScreenShot(GenericType.java:419)
at Generic.pack.GenericType.softAssert(GenericType.java:399)
at step.base.pack.StepBase.MainLooper(StepBase.java:113)
at step.base.pack.StepBase.Step(StepBase.java:40)
at Specifics.pack.SpecificType.login(SpecificType.java:98)
at step.base.pack.StepBase.MainLooper(StepBase.java:122)
at step.base.pack.StepBase.keyword(StepBase.java:50)
at wave.test.cases.TestSuite.WAVE_TC_02(TestSuite.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WAVE_TC_02 -->
        <test-method is-config="true" signature="Teardown(org.testng.ITestResult)[pri:0, instance:wave.test.cases.TestSuite@69504ae9]" started-at="2020-10-08T15:15:30 IST" name="Teardown" finished-at="2020-10-08T15:15:35 IST" duration-ms="4852" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=WAVE_TC_02 status=FAILURE method=TestSuite.WAVE_TC_02()[pri:2, instance:wave.test.cases.TestSuite@69504ae9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Teardown -->
      </class> <!-- wave.test.cases.TestSuite -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
